name:  SEMBI x InvisiRisk 

on:
  schedule:
    - cron: '10 3 * * *'  # Runs daily at 8:30 AM Nepal Time
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
         git config user.name "ir-pranesh-shrestha"
          git config user.email "pranesh.shrestha@invisirisk.com"
          
      - name: Add upstream and sync fork
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          git remote add upstream https://github.com/gurock/trcli.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/ir-pranesh-shrestha/trcli-Sembi main
          
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_PROD }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
